### PR TITLE
[RFC] Guzzle 6

### LINKED ISSUE #19: jcroll/foursquare-api-client v2.1.1 requires guzzlehttp/guzzle ~4|~5
Hello, I try to upgrade a projet of mine, but I can't use foursquare-api-client. Here is my error message :

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jcroll/foursquare-api-client v2.1.1 requires guzzlehttp/guzzle ~4|~5 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - jcroll/foursquare-api-client v2.1.0 requires guzzlehttp/guzzle ~4|~5 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for jcroll/foursquare-api-client ^2.1 -> satisfiable by jcroll/foursquare-api-client[v2.1.0, v2.1.1].
```

I use guzzlehttp/guzzle ^6.2, what can I do ?

### PR DESCRIPTION
**Pull request by jcroll**
Fixes #19

### CODE REVIEW

**Comment by jcroll** [comment]
This ticket is dependent on the resolution of this issue https://github.com/guzzle/guzzle-services/issues/89

**Comment by tentacode** [comment]
issue as been closes in guzzle/guzzle-services#89

is this mergeable ? waiting for this to be able to update :) thanks for your work

**Comment by jcroll** [comment]
No @tentacode it's not ready. Thanks for the heads up btw.

If you want to try and complete it you'd just have to get the composer install working, in other words, get a new `composer.lock` file to generate with the new dependencies. Then test that it works.

It wouldn't be a lot of work. I will get to it eventually but very busy atm.

If you choose to pursue it please submit as a new pr and I will get it merged.

Thanks,

J

**Comment by jcroll** [comment]
@tentacode I have upgraded to Guzzle 6 https://github.com/jcroll/foursquare-api-client/tree/v3.0.0

**Pull request merged**
