### PR TITLE
[RFC] Update the way default params are set for the client. Should fix #21

### LINKED ISSUE #21: cURL error 6: Couldn't resolve host
@jcroll , I'm using your bundle for symfony. 
I get an error `There was an error executing the venues/explore command: cURL error 6: Couldn't resolve host 'venues' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`
Example of usage is here: https://github.com/jcroll/foursquare-api-bundle/issues/8#issuecomment-272698902
I've used some debuggers and realized that baseUri in Description is empty, so I added `baseUri` to `client.json` and it works, but then I've got 'missing credentials', so query parameters are not passed. 
Tested on different laptops with different configuration  - same result (v.3)
v2.1.1 works perfect

### PR DESCRIPTION
**Pull request by hpatoio**
This still need a bit of work but I wanted you to have a look and start to give feedbacks.

I had the same issue as @kopaygorodsky in #21
 
Something has probably changed in the Guzzle description https://github.com/guzzle/guzzle-services/issues/100

### CODE REVIEW

**Comment by jcroll** [comment]
Thanks @hpatoio. Have you tested your code over http? Does it successfully communicate with the foursquare endpoints?

**Comment by hpatoio** [comment]
@jcroll I've tested in my project and everything works. If you want to introduce some functional test for your client with real HTTP connections you can do the same way I do for the `Bitly API client" [here](https://github.com/hpatoio/bitly-api#behat)

**Comment by stloyd** [comment]
I can confirm that those changes fix the #21 issue for me too.

**Comment by jcroll** [comment]
Fixes #21 

👍  thanks @hpatoio

**Pull request merged**
